version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
      - checkout
      - run:
          name: docker build & push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./build.sh --push
